<?php

namespace FMR\ChantierBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FournitureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FournitureRepository extends EntityRepository
{
}
