home:
    pattern:  /
    defaults: { _controller: FMRCommonBundle:Default:index }
    
fmr_facture:
    resource: "@FMRFactureBundle/Controller/"
    type:     annotation
    prefix:   /

fmr_chantier:
    resource: "@FMRChantierBundle/Controller/"
    type:     annotation
    prefix:   /

fmr_offre:
    resource: "@FMROffreBundle/Controller/"
    type:     annotation
    prefix:   /

fmr_client:
    resource: "@FMRClientBundle/Controller/"
    type:     annotation
    prefix:   /

fmr_common:
    resource: "@FMRCommonBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
