security:
    encoders:
         FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
            
    firewalls:
        assets:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
            anonymous:  ~
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path: /
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_wdt, roles: 'IS_AUTHENTICATED_ANONYMOUSLY' } 
        - { path: ^/_configurator, roles: 'IS_AUTHENTICATED_ANONYMOUSLY' } 
        - { path: ^/, role: ROLE_USER }
